version: "3.9"  # optional since v1.27.0
services:
  web:
    build: .
    ports:
      - "8080:8080"
    networks:
      - main
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
    networks:
      - main
# volumes:
#   logvolume01: {}
networks:
  main:
