global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: myhost
    metrics_path: '/metrics'
    static_configs:
      - targets: ['web:8080', 'cache:8080']
